CREATE TABLE IF NOT EXISTS users(
    user_id serial PRIMARY KEY,
    username CHARACTER VARYING UNIQUE NOT NULL,
    password CHARACTER VARYING NOT NULL,
    email CHARACTER VARYING UNIQUE NOT NULL
);